id: I3E3F67A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:31:27+00:00'
last_modified: '2022-06-07T17:32:43.115985+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8601
  title: གདན་ས་ཆེན་པོ་དཔལ་ལྡན་ས་སྐྱ་དགོན་གྱི་དཔེ་རྙིང་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    013C:
      image_group_id: I3CN21135
      title: ''
      total_pages: 1456
      order: 1
      base_file: 013C.txt
    3BA0:
      image_group_id: I3CN21136
      title: ''
      total_pages: 1412
      order: 2
      base_file: 3BA0.txt
    DCFE:
      image_group_id: I3CN21137
      title: ''
      total_pages: 1400
      order: 3
      base_file: DCFE.txt
    6E32:
      image_group_id: I3CN21138
      title: ''
      total_pages: 1396
      order: 4
      base_file: 6E32.txt
    E3AC:
      image_group_id: I3CN21139
      title: ''
      total_pages: 1374
      order: 5
      base_file: E3AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
